#!/usr/bin/env bb

(ns install-hooks
  (:require [babashka.fs :as fs]
            [clojure.java.io :as io]))

(def cwd (System/getProperty "user.dir"))
(def hooks-dir (fs/path cwd ".git" "hooks"))
(def hook-path (fs/path hooks-dir "pre-commit"))
(def hook-script "#!/bin/sh\n# Auto-generated by scripts/install-hooks.clj\n\nnpm run test\nnpm run lint\nnpm run typecheck\n")

(defn install-hooks []
  (if-not (fs/exists? hooks-dir)
    (println "No .git/hooks directory found. Skipping hook installation.")
    (try
      (spit (str hook-path) hook-script)
      ;; Make the hook executable
      (.setExecutable (io/file (str hook-path)) true)
      (println "Successfully installed pre-commit hook.")
      (catch Exception e
        (println "Failed to install pre-commit hook:" (.getMessage e))))))

(install-hooks)
